### ISSUE TITLE
Adhere to either CamelCase or snake_case consistently while naming ...

### ISSUE THREAD

**Issue by kedarmhaswade** [vapporwashmade/javascript-projects#12]
See: https://github.com/vapporwashmade/javascript-projects/blob/773fe42ece458b668c80285702e9e0e386cb73de/algods/binarySearch/binarySearch_iterative.js#L5

Here, you use a combination of both camel-casing and snake-casing (look up what these mean) while naming your function. Whereas it is a matter of _style_ and a style-checking tool (sometimes called a linter, look up JSLint, or JSHint) will flag this inconsistency, it is a good idea to be consistent to begin with. I guess in JavaScript the incumbent style for function names is _CamelCase_. While it is more significant in case of naming functions and modules, it is also important while naming variables and properties. Look at your variables `low` and `high`. It is fine to have some convention here too. The convention you have followed is that `low` is the _inclusive_ index, whereas `high` is an _exclusive_ index (meaning `a[high]` does not exist and will be returning as `undefined` in a forgiving language like JavaScript). By making this _convention_ or a programming _assumption_ more explicit in the form of a documenting comment makes the code more readable.

**Comment by vapporwashmade** [comment]
OK fixed it
