### ISSUE TITLE
Required reading and discussion ...

### ISSUE THREAD

**Issue by kedarmhaswade** [vapporwashmade/javascript-projects#14]
https://github.com/vapporwashmade/javascript-projects/blob/773fe42ece458b668c80285702e9e0e386cb73de/algods/binarySearch/binarySearch_iterative.js#L8

Programming is hard. Look at the above line which you think to be correct. And after you have convinced yourself that it is, read [this article](https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html) and reconsider. (Let me know if you don't understand something from it).

A (life) lesson here is that always be smart, but seldom be certain.

**Comment by vapporwashmade** [comment]
Yes I will add to it right now.
